# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lVa-ds6d1LXobqjsq9GzOmTEO1boUX5h
"""

import zipfile
import json
import pandas as pd
import heapq
import os

print("1. Extracting the dataset...")
zip_path = '[PUB] India_runs_data_and_ai_challenge.zip'
extracted_path = 'candidates.jsonl'

# Unzip the file directly in Colab
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    for member in zip_ref.namelist():
        if member.endswith('candidates.jsonl'):
            zip_ref.extract(member, '.')
            os.rename(member, extracted_path)
            break

def is_honeypot(candidate):
    # Detects impossible profiles (e.g. Expert skills with 0 months experience)
    for skill in candidate.get("skills", []):
        if skill.get("proficiency") in ["expert", "advanced"] and skill.get("duration_months", 0) <= 0:
            return True
    return False

def has_only_consulting_experience(history):
    # Disqualifies candidates with only consulting experience per JD
    consulting_firms = {"TCS", "Infosys", "Wipro", "Accenture", "Cognizant", "Capgemini"}
    if not history: return False
    companies = {job.get("company", "") for job in history}
    return companies.issubset(consulting_firms)

def score_candidate(candidate):
    profile = candidate.get("profile", {})
    history = candidate.get("career_history", [])
    skills = candidate.get("skills", [])
    signals = candidate.get("redrob_signals", {})

    if is_honeypot(candidate): return 0.0
    if has_only_consulting_experience(history): return 0.0

    yoe = profile.get("years_of_experience", 0)
    if yoe < 4 or yoe > 12: return 0.0

    score = 0.0

    # JD Required Skills
    target_skills = {"Pinecone", "Weaviate", "Qdrant", "Milvus", "OpenSearch", "Elasticsearch", "FAISS", "Python", "Embeddings", "Information Retrieval"}
    skill_score = 0
    candidate_skills = {s["name"]: s["proficiency"] for s in skills}

    for skill, prof in candidate_skills.items():
        if skill in target_skills:
            if prof in ["expert", "advanced"]: skill_score += 0.2
            elif prof == "intermediate": skill_score += 0.1
    score += min(skill_score, 0.4)

    # Trajectory & History
    trajectory_score = 0.0
    if 5 <= yoe <= 9: trajectory_score += 0.15

    for job in history:
        title = job.get("title", "").lower()
        desc = job.get("description", "").lower()
        if any(x in title for x in ["ai", "machine learning", "ml", "search", "recommendation", "nlp"]):
            trajectory_score += 0.1
        if any(x in desc for x in ["embedding", "retrieval", "ranking", "ndcg", "production", "vector"]):
            trajectory_score += 0.1
    score += min(trajectory_score, 0.35)

    # Redrob Behavioral Signals Multiplier
    behavioral_score = 0.0
    response_rate = signals.get("recruiter_response_rate", 0)
    if response_rate > 0.6: behavioral_score += 0.15
    elif response_rate > 0.3: behavioral_score += 0.05

    if signals.get("github_activity_score", -1) > 20: behavioral_score += 0.10

    score += min(behavioral_score, 0.25)

    return score

def generate_reasoning(candidate, score):
    yoe = candidate['profile'].get('years_of_experience', 0)
    title = candidate['profile'].get('current_title', 'Engineer')
    response_rate = int(candidate['redrob_signals'].get('recruiter_response_rate', 0) * 100)
    return f"{title} with {yoe} years of experience. Strong match for core JD requirements with a {response_rate}% recruiter response rate ensuring high availability."

print("2. Scoring 100,000 candidates (This will take ~30 seconds)...")
top_k = []
with open(extracted_path, 'r') as f:
    for line in f:
        if line.strip():
            c = json.loads(line)
            score = score_candidate(c)
            if score > 0:
                # Keep only top 100 in memory to stay ultra-fast
                if len(top_k) < 100:
                    heapq.heappush(top_k, (score, c['candidate_id'], generate_reasoning(c, score)))
                else:
                    heapq.heappushpop(top_k, (score, c['candidate_id'], generate_reasoning(c, score)))

# Sort the final top 100
top_k.sort(reverse=True)

results = []
for i, (score, cid, reasoning) in enumerate(top_k):
    results.append({
        "candidate_id": cid,
        "rank": i + 1,
        "score": round(score, 4),
        "reasoning": reasoning
    })

print("3. Generating final submission CSV...")
df = pd.DataFrame(results)
df.to_csv("team_submission.csv", index=False)
print("✅ DONE! Refresh your file panel on the left to download 'team_submission.csv'!")